// new_frontend/js/api.js
const API_BASE_URL = 'http://127.0.0.1:8000';

class ApiService {
    /**
     * Centralized request handler with dynamic Token injection.
     */
    static async request(endpoint, options = {}) {
        const url = `${API_BASE_URL}${endpoint}`;
        // Retrieve the token generated by your Bcrypt login logic
        const token = localStorage.getItem('auth_token') || 'hackathon-secret';

        const headers = {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`,
            ...(options.headers || {})
        };

        const config = { ...options, headers };

        try {
            const response = await fetch(url, config);
            const data = await response.json();

            if (!response.ok) {
                throw new Error(data.error || data.message || `HTTP error! status: ${response.status}`);
            }
            return { ok: true, data };
        } catch (error) {
            console.error(`🚨 API Error on ${endpoint}:`, error);
            return { ok: false, error: error.message };
        }
    }

    static async login(data) { return this.request('/auth/login', { method: 'POST', body: JSON.stringify(data) }); }
    static async register(data) { return this.request('/auth/register', { method: 'POST', body: JSON.stringify(data) }); }
    static async getDashboard() { return this.request('/dashboard'); }
    static async getReports() { return this.request('/dashboard/reports'); }
    static async registerNGO(data) { return this.request('/ngo/register', { method: 'POST', body: JSON.stringify(data) }); }

    /**
     * Parallel fetch for NGO profile + global stats.
     */
    static async getNGODashboard(ngoId) {
        const response = await this.request(`/ngo/${ngoId}/dashboard`);
        if (!response.ok) {
            throw new Error(response.error || 'Unable to load NGO dashboard');
        }
        return response.data;
    }

    static async postNeed(data) {
        return this.request('/need', { method: 'POST', body: JSON.stringify(data) });
    }

    static async postVolunteer(data) {
        return this.request('/volunteer', { method: 'POST', body: JSON.stringify(data) });
    }

    static async runMatch() { return this.request('/match'); }
}
window.ApiService = ApiService;
window.api = ApiService;