apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: setu-api
spec:
  template:
    spec:
      containers:
        - env:
          - name: FIREBASE_PROJECT_ID
            value: "project-ecb78041-2b9f-43b6-a06"
          - name: GEMINI_API_KEY
            value: "AIzaSyDFJ9z0bB4hG6ABZWqoYNeZ-wJn97FyCnU"
          - name: GMAIL_SENDER
            value: "setuofficial205@gmail.com"
          - name: GMAIL_APP_PASSWORD
            value: "yosegkdaqvvusjcq"
          - name: SECRET_TOKEN
            value: "hackathon-secret"
          - name: WEATHER_API
            value: "4064f6da5a6666a54724151c1e71c904"
          - name: GOOGLE_MAPS_KEY
            value: "AIzaSyBjn6bIOP1FtwRJpTv7RvsjubLDlwGx7Z0"
          - name: SETU_API_BASE_URL
            value: "https://setu-api-949977701091.asia-south1.run.app"
